### ISSUE TITLE
getenv function always returns null

### ISSUE THREAD

**Issue by factorin-j** [pinodex/openshift-cartridge-nginx-php7#4]
please help! using `getenv` function in your gear returns `null` if the env is set using `rhc set-env` command 🙇  I tried to restart the app but still no luck 🙇

**Comment by pinodex** [comment]
This can be fixed by adding `clear_env = no` to the php-fpm config file.

SSH to your app and edit `~/nginx-php7/etc/www.conf.erb` then add this line:

```
clear_env = no
```

Followed by these commands:

```
$ build_config
$ service php-fpm restart
```

This was also addressed at @14119d67d1e4ab8ec2913c37bfa076073badbd0d. Be sure to restart your app or just the php-fpm through SSH after modifying your env.

**Comment by factorin-j** [comment]
oh, thank you very much 🙇
