### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by limatheus** [pinodex/openshift-cartridge-nginx-php7#7]
Hi, 
First I need say thanks for this cartridge, it's awesome. Thank you.

Here is my problem, when I try deploy a Laravel app to the Openshift any route except '/' returns me a 404 error.

I try some things, like: in `/template/config/nginx.d/default.conf.erb` change the `try_files $uri =404;`

To `try_files $uri $uri/ /index.php?$query_string;` 
Or `try_files $uri $uri/ /index.php$is_args$args;` 

I try many others ways, but nothing.

Can you help me?

**Comment by pinodex** [comment]
Is the 404 error from Nginx or Laravel?

**Comment by limatheus** [comment]
@pinodex It's from Nginx.
In localhost (also PHP 7.0.8 and Nginx) work's pretty fine, any route is accessible.

**Comment by pinodex** [comment]
I'm using this for my Laravel app

```
location / {
    try_files $uri $uri/ /index.php$is_args$args;
}
```

Check if the deployed config file is the one you edited. If you are creating the app with this cartridge (not forked), clone your OpenShift app, then edit `config/nginx.d/default.conf.erb`. Otherwise, if you are creating from a fork of this cartridge, make sure to change the cartridge definition to `http://cartreflect-claytondev.rhcloud.com/github/<username>/openshift-cartridge-nginx-php7`.

**Comment by limatheus** [comment]
Ok, I will try this.
Thanks in advance.

**Comment by baddwin** [comment]
```
    try_files $uri $uri/ /index.php$is_args$args;
```
that should be written in the template file instead of `try_files $uri $uri/ =404;`
